[package]
name = "merino"
version = "0.1.3.3"
description = "A SOCKS5 Proxy server written in Rust"
repository = "https://github.com/ajmwagar/merino"
readme = "README.md"
license = "MIT"
authors = ["Avery Wagar <ajmw.subs@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 3
lto = true

[dependencies]
clap = { version = "3.2.25", features = ["derive"] }
csv = "1.3.0"
log = "0.4.20"
pretty_env_logger = "0.5.0"
serde = "1.0.193"
serde_derive = "1.0.193"
snafu = "0.7.5"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full"] }
